version: 2
jobs:
  build:
    working_directory: /build_arch_go
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build arch_go images
          command: pwd && sh script/build_new_tags.sh

workflows:
   version: 2
   check_and_build:
     triggers:
       - schedule:
           cron: "15 * * * *"
           filters:
            branches:
              only:
                - master
     jobs:
       - build
